"""Emoji → Tabler Icons mapping and text-segmentation utilities.

Maps Unicode emoji sequences to Tabler Icons *outline* icon names.
``split_text_emoji()`` splits a string into alternating plain-text and
icon-name segments suitable for inline rendering in the Pillow pipeline.

Pre-baked 64×64 RGBA PNGs live in ``app/assets/icons/emoji/`` and are
generated by ``scripts/bake_emoji_icons.py`` (dev-only, needs cairosvg).
"""
from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

from app.renderer.tokens import ICONS_DIR

if TYPE_CHECKING:
    from PIL import Image

# Available pre-baked icon sizes (checked in order; first match wins).
# Sources live at  app/assets/icons/<size>/<name>.png
_ICON_FALLBACK_SIZES: tuple[int, ...] = (16, 24, 32, 48, 64)

# ---------------------------------------------------------------------------
# Emoji → Tabler outline icon name
#
# Keys  : Unicode emoji sequences (may be multi-codepoint).
#         Longer sequences are tried before shorter ones (greedy match).
# Values: Tabler outline icon stem, e.g. "heart" → heart.png / heart.svg
# ---------------------------------------------------------------------------

EMOJI_TO_ICON: dict[str, str] = {
    # ------------------------------------------------------------------
    # Hearts
    # ------------------------------------------------------------------
    "❤️": "heart",   # U+2764 U+FE0F  red heart + variation selector
    "❤": "heart",    # U+2764         bare red heart
    "🧡": "heart",
    "💛": "heart",
    "💚": "heart",
    "💙": "heart",
    "💜": "heart",
    "🖤": "heart",
    "🤍": "heart",
    "🤎": "heart",
    "💗": "heart",
    "💓": "heart",
    "💕": "heart",
    "💞": "heart",
    "💝": "heart",
    "💘": "heart",
    "💖": "heart",
    "💟": "heart",
    "💔": "heart-broken",
    "🩷": "heart",
    "🩶": "heart",
    "🩵": "heart",
    "🫀": "heart",

    # ------------------------------------------------------------------
    # Smileys — happy / love
    # ------------------------------------------------------------------
    "😀": "mood-happy",
    "😃": "mood-happy",
    "😄": "mood-crazy-happy",
    "😁": "mood-happy",
    "😆": "mood-crazy-happy",
    "😅": "mood-smile",
    "🤣": "mood-crazy-happy",
    "😂": "mood-crazy-happy",
    "🙂": "mood-smile",
    "🙃": "mood-tongue",
    "😉": "mood-wink",
    "😊": "mood-smile-beam",
    "😇": "mood-nerd",
    "🥰": "hearts",
    "😍": "mood-heart",
    "🤩": "star",
    "😘": "mood-heart",
    "😗": "mood-smile",
    "😙": "mood-smile",
    "😚": "mood-smile",

    # Smileys — playful
    "😋": "mood-tongue",
    "😛": "mood-tongue",
    "😜": "mood-tongue-wink",
    "🤪": "mood-crazy-happy",
    "😝": "mood-tongue",
    "🤗": "mood-smile",
    "🤭": "mood-wink",
    "🤫": "mood-empty",
    "🤔": "mood-confuzed",
    "🤐": "mood-empty",
    "🤨": "mood-puzzled",
    "😐": "mood-neutral",
    "😑": "mood-neutral",
    "😶": "mood-empty",
    "😏": "mood-wink",

    # Smileys — negative / sick
    "😒": "mood-unamused",
    "😞": "mood-sad",
    "😔": "mood-sad",
    "😪": "mood-sad",
    "😴": "zzz",
    "🥱": "zzz",
    "😷": "mood-sick",
    "🤒": "mood-sick",
    "🤕": "mood-sick",
    "🤢": "mood-sick",
    "🤧": "mood-sick",
    "🥵": "flame",
    "🥶": "snowflake",
    "🥴": "mood-sick",
    "😵": "mood-x",
    "😎": "mood-nerd",
    "🤓": "mood-nerd",
    "🧐": "mood-nerd",
    "😕": "mood-confuzed",
    "😟": "mood-sad",
    "🙁": "mood-sad",
    "☹️": "mood-sad",
    "☹": "mood-sad",
    "😮": "mood-surprised",
    "😯": "mood-surprised",
    "😲": "mood-surprised",
    "😳": "mood-puzzled",
    "🥺": "mood-sad",
    "😦": "mood-sad",
    "😧": "mood-confuzed",
    "😨": "mood-x",
    "😰": "mood-sad",
    "😥": "mood-sad",
    "😢": "mood-sad",
    "😭": "mood-sad",
    "😱": "mood-x",
    "😖": "mood-sick",
    "😣": "mood-sad",
    "😓": "mood-sad",
    "😩": "mood-sad",
    "😫": "mood-sad",
    "😤": "mood-wrrr",
    "😡": "mood-wrrr",
    "😠": "mood-wrrr",
    "🤬": "mood-x",
    "😈": "mood-x",
    "👿": "mood-x",
    "💀": "skull",
    "☠️": "skull",
    "☠": "skull",
    "🤖": "robot",
    "👻": "ghost",

    # ------------------------------------------------------------------
    # Gestures & body
    # ------------------------------------------------------------------
    "👍": "thumb-up",
    "👎": "thumb-down",
    "👏": "hand-stop",
    "🤝": "hand-grab",
    "🙏": "pray",
    "💪": "hand-grab",
    "✋": "hand-stop",
    "🖐️": "hand-stop",
    "🖐": "hand-stop",
    "✌️": "peace",
    "✌": "peace",
    "🤞": "hand-two-fingers",
    "👋": "wave-saw-tool",
    "👁️": "eye",
    "👁": "eye",

    # ------------------------------------------------------------------
    # People
    # ------------------------------------------------------------------
    "👶": "baby-carriage",
    "🧑": "user",
    "👦": "user",
    "👧": "user",
    "👨": "user",
    "👩": "user",
    "👴": "user",
    "👵": "user",
    "👫": "users",
    "👬": "users",
    "👭": "users",
    "💏": "heart",
    "💑": "hearts",
    "👪": "users",
    "🧍": "user",
    "🧎": "user",

    # ------------------------------------------------------------------
    # Animals
    # ------------------------------------------------------------------
    "🐶": "dog",
    "🐕": "dog",
    "🐩": "dog",
    "🦮": "dog",
    "🐱": "cat",
    "🐈": "cat",
    "🐟": "fish",
    "🐠": "fish",
    "🐡": "fish",
    "🐾": "paw",

    # ------------------------------------------------------------------
    # Nature / Plants
    # ------------------------------------------------------------------
    "🌱": "leaf",
    "🌿": "leaf",
    "🍃": "leaf",
    "🍂": "leaf",
    "🍁": "leaf",
    "🌲": "tree",
    "🌳": "tree",
    "🌴": "tree",
    "🎄": "christmas-tree",
    "🌸": "flower",
    "🌹": "flower",
    "🌺": "flower",
    "🌼": "flower",
    "🌻": "flower",
    "🌷": "flower",
    "💐": "flower",
    "🥀": "flower",
    "☘️": "clover",
    "☘": "clover",
    "🍀": "clover",
    "🍄": "mushroom",
    "🌾": "wheat",

    # ------------------------------------------------------------------
    # Weather / Sky
    # ------------------------------------------------------------------
    "☀️": "sun",
    "☀": "sun",
    "🌞": "sun",
    "🌤️": "cloud",
    "🌤": "cloud",
    "⛅": "cloud",
    "🌥️": "cloud",
    "🌥": "cloud",
    "☁️": "cloud",
    "☁": "cloud",
    "🌦️": "cloud-rain",
    "🌦": "cloud-rain",
    "🌧️": "cloud-rain",
    "🌧": "cloud-rain",
    "⛈️": "cloud-storm",
    "⛈": "cloud-storm",
    "🌩️": "bolt",
    "🌩": "bolt",
    "🌨️": "cloud-snow",
    "🌨": "cloud-snow",
    "❄️": "snowflake",
    "❄": "snowflake",
    "⛄": "snowflake",
    "☃️": "snowflake",
    "☃": "snowflake",
    "💨": "wind",
    "🌬️": "wind",
    "🌬": "wind",
    "🌪️": "tornado",
    "🌪": "tornado",
    "🌊": "wave-sine",
    "🌈": "rainbow",

    # Sky / Space
    "🌙": "moon",
    "🌛": "moon",
    "🌜": "moon",
    "🌝": "moon",
    "🌚": "moon",
    "🌕": "moon",
    "🌑": "moon",
    "⭐": "star",
    "🌟": "stars",
    "💫": "star",
    "✨": "sparkles",
    "🔥": "flame",

    # ------------------------------------------------------------------
    # Food & Drink
    # ------------------------------------------------------------------
    "🎂": "cake",
    "🍰": "cake",
    "🧁": "cake",
    "🍕": "pizza",
    "🍞": "bread",
    "🥐": "bread",
    "☕": "coffee",
    "🍵": "coffee",
    "🍺": "beer",
    "🍻": "beer",
    "🥂": "glass-full",
    "🍷": "glass-champagne",
    "🍾": "bottle",
    "🥃": "glass-full",
    "🍎": "apple",
    "🍏": "apple",
    "🍒": "cherry",

    # ------------------------------------------------------------------
    # Activities / Sports
    # ------------------------------------------------------------------
    "⚽": "ball-football",
    "🏀": "ball-basketball",
    "🎾": "ball-tennis",
    "⚾": "ball-baseball",
    "🏐": "ball-volleyball",
    "🏈": "ball-american-football",
    "🎱": "ball-bowling",
    "🚴": "bike",
    "🚴‍♂️": "bike",
    "🚴‍♀️": "bike",
    "🏊": "swimming",
    "🏊‍♂️": "swimming",
    "🏊‍♀️": "swimming",
    "🎮": "device-gamepad",
    "🕹️": "device-gamepad",
    "🕹": "device-gamepad",
    "♟️": "chess",
    "♟": "chess",
    "🎭": "theater",
    "🎨": "palette",
    "🎵": "music",
    "🎶": "music",
    "🎸": "guitar-pick",
    "🎹": "piano",
    "🎤": "microphone",
    "🎧": "headphones",
    "🎬": "movie",
    "📸": "camera",
    "📷": "camera",

    # ------------------------------------------------------------------
    # Travel & Places
    # ------------------------------------------------------------------
    "✈️": "plane",
    "✈": "plane",
    "🛫": "plane-departure",
    "🛬": "plane-arrival",
    "🚂": "train",
    "🚄": "train",
    "🚅": "train",
    "🚇": "train",
    "🚌": "bus",
    "🚑": "ambulance",
    "🚒": "firetruck",
    "🚗": "car",
    "🚙": "car",
    "🛻": "car",
    "🛵": "motorbike",
    "🏍️": "motorbike",
    "🏍": "motorbike",
    "🛴": "scooter",
    "🚲": "bike",
    "🚁": "helicopter",
    "⛵": "sailboat",
    "🚤": "sailboat",
    "🛳️": "ship",
    "🛳": "ship",
    "🏠": "home",
    "🏡": "home",
    "🏢": "building",
    "🏥": "building-hospital",
    "🏦": "building-bank",
    "🏨": "building",
    "🏪": "building-store",
    "🏫": "school",
    "🏭": "building-factory",
    "🏯": "tower",
    "🏰": "tower",
    "⛪": "building-church",
    "🌍": "world",
    "🌎": "world",
    "🌏": "world",
    "🗺️": "map",
    "🗺": "map",
    "📍": "map-pin",
    "📌": "map-pin",
    "🏔️": "mountain",
    "🏔": "mountain",
    "⛰️": "mountain",
    "⛰": "mountain",
    "🌋": "mountain",
    "🏕️": "tent",
    "🏕": "tent",
    "🏖️": "beach",
    "🏖": "beach",
    "🏝️": "beach",
    "🏝": "beach",
    "🏞️": "mountain",
    "🏞": "mountain",

    # ------------------------------------------------------------------
    # Objects — tech
    # ------------------------------------------------------------------
    "📱": "device-mobile",
    "📲": "device-mobile",
    "💻": "device-laptop",
    "🖥️": "device-desktop",
    "🖥": "device-desktop",
    "🖨️": "printer",
    "🖨": "printer",
    "⌨️": "keyboard",
    "⌨": "keyboard",
    "🖱️": "mouse",
    "🖱": "mouse",
    "📡": "antenna",
    "📹": "video",
    "🎥": "video",
    "💾": "device-floppy",
    "💿": "disc",
    "📀": "disc",
    "☎️": "phone",
    "☎": "phone",
    "📞": "phone-call",
    "📺": "device-tv",

    # Objects — time
    "⏱️": "clock",
    "⏱": "clock",
    "⏲️": "clock",
    "⏲": "clock",
    "⏰": "alarm",
    "🕰️": "clock",
    "🕰": "clock",
    "⌚": "clock",
    "⏳": "hourglass",
    "⌛": "hourglass",

    # Objects — office / stationery
    "📅": "calendar",
    "📆": "calendar",
    "🗓️": "calendar",
    "🗓": "calendar",
    "📋": "clipboard",
    "✂️": "scissors",
    "✂": "scissors",
    "🔑": "key",
    "🗝️": "key",
    "🗝": "key",
    "🔒": "lock",
    "🔓": "lock-open",
    "🔔": "bell",
    "🔕": "bell-off",
    "🔇": "volume-off",
    "🔊": "volume",
    "📢": "speakerphone",
    "📣": "speakerphone",
    "📖": "book",
    "📚": "books",
    "📝": "pencil",
    "✏️": "pencil",
    "✏": "pencil",
    "🖊️": "pencil",
    "🖊": "pencil",
    "🖋️": "pencil",
    "🖋": "pencil",
    "🖌️": "paint",
    "🖌": "paint",
    "💡": "bulb",
    "🔦": "lamp",
    "🕯️": "candle",
    "🕯": "candle",
    "🔭": "telescope",
    "🔬": "microscope",
    "📁": "folder",
    "📂": "folder",
    "🗑️": "trash",
    "🗑": "trash",

    # Objects — tools / workshop
    "🔧": "tool",
    "🔨": "hammer",
    "🪛": "tool",
    "⚙️": "settings",
    "⚙": "settings",

    # Objects — health
    "💊": "pill",
    "💉": "vaccine",
    "🩺": "stethoscope",
    "🩹": "bandage",
    "🧬": "dna",
    "🧪": "flask",
    "⚗️": "flask",
    "⚗": "flask",

    # Objects — money / finance
    "💰": "coin",
    "💵": "currency-dollar",
    "💶": "currency-euro",
    "💷": "currency-pound",
    "💳": "credit-card",

    # Objects — awards / celebration
    "🏆": "trophy",
    "🥇": "medal",
    "🥈": "medal",
    "🥉": "medal",
    "🎖️": "medal",
    "🎖": "medal",
    "🎗️": "ribbon-health",
    "🎗": "ribbon-health",
    "🎫": "ticket",
    "🎟️": "ticket",
    "🎟": "ticket",
    "💎": "diamond",
    "👑": "crown",

    # ------------------------------------------------------------------
    # Celebration / special occasions
    # ------------------------------------------------------------------
    "🎉": "confetti",
    "🎊": "confetti",
    "🎈": "balloon",
    "🎁": "gift",
    "🎀": "gift",
    "🎓": "certificate",
    "💼": "briefcase",

    # ------------------------------------------------------------------
    # Symbols / signs
    # ------------------------------------------------------------------
    "✅": "circle-check",
    "☑️": "checkbox",
    "☑": "checkbox",
    "❌": "circle-x",
    "❎": "circle-x",
    "⚠️": "alert-triangle",
    "⚠": "alert-triangle",
    "ℹ️": "info-circle",
    "ℹ": "info-circle",
    "🔴": "circle-dot",
    "🟢": "circle-check",
    "🔵": "circle-dot",
    "⚫": "circle-dot",
    "⚪": "circle",
    "🔺": "triangle",
    "💯": "check",
    "⬆️": "arrow-up",
    "⬆": "arrow-up",
    "➡️": "arrow-right",
    "➡": "arrow-right",
    "⬇️": "arrow-down",
    "⬇": "arrow-down",
    "⬅️": "arrow-left",
    "⬅": "arrow-left",
    "↕️": "arrows-vertical",
    "↕": "arrows-vertical",
    "↔️": "arrows-horizontal",
    "↔": "arrows-horizontal",
    "🔃": "refresh",
    "🔄": "refresh",
    "⛔": "circle-x",
    "🚫": "circle-x",
    "🚩": "flag-2",
    "🏳️": "flag",
    "🏴": "flag",
    "🎌": "flag",
    "📳": "device-mobile",
    "📴": "device-mobile-off",
    "🔞": "rating-18-plus",
    "♻️": "recycle",
    "♻": "recycle",
    "✔️": "check",
    "✔": "check",
    "➕": "plus",
    "➖": "minus",
    "❓": "question-mark",
    "❗": "exclamation-mark",
    "‼️": "exclamation-mark",
    "‼": "exclamation-mark",
    "💬": "message",
    "💭": "message-circle",
    "🗯️": "message-circle",
    "🗯": "message-circle",
    "📧": "mail",
    "📩": "mail",
    "📨": "mail",
    "📤": "send",
    "📥": "inbox",
    "🔗": "link",
    "🔖": "bookmark",
    "🏷️": "tag",
    "🏷": "tag",
    "🔍": "search",
    "🔎": "search",
    "📊": "chart-bar",
    "📈": "chart-line",
    "📉": "chart-line",
    "🗒️": "notes",
    "🗒": "notes",
    "📌": "map-pin",
}

# ---------------------------------------------------------------------------
# Internal: sorted keys for greedy longest-match (longest first)
# ---------------------------------------------------------------------------

_SORTED_KEYS: tuple[str, ...] = tuple(
    sorted(EMOJI_TO_ICON.keys(), key=len, reverse=True)
)


def _is_strippable_emoji(cp: int) -> bool:
    """Return True for code points that should be silently consumed when
    they are not covered by *EMOJI_TO_ICON* (they would render as □)."""
    return (
        0x1F000 <= cp <= 0x1FFFF    # Main emoji pictographs
        or 0x1F3FB <= cp <= 0x1F3FF  # Skin-tone modifiers
        or 0x1F1E0 <= cp <= 0x1F1FF  # Regional indicators (flags)
        or 0xFE00 <= cp <= 0xFE0F    # Variation selectors VS1-VS16
        or cp == 0x200D              # Zero-width joiner
        or cp == 0x20E3              # Combining enclosing keycap
        or 0xE0000 <= cp <= 0xE007F  # Tag characters (flag sequences)
    )


def split_text_emoji(text: str) -> list[tuple[str, str]]:
    """Split *text* into alternating ``("text", str)`` / ``("icon", name)`` segments.

    Emoji sequences present in :data:`EMOJI_TO_ICON` become icon segments
    (the value is the Tabler icon stem name).  Emoji characters that are
    *not* in the mapping are silently discarded so they don't appear as
    □ replacement glyphs in fonts that lack emoji support.
    """
    segments: list[tuple[str, str]] = []
    buf = ""
    i = 0
    n = len(text)

    while i < n:
        # Greedy longest-first match against the known-emoji dict
        matched = False
        for key in _SORTED_KEYS:
            klen = len(key)
            if text[i : i + klen] == key:
                if buf:
                    segments.append(("text", buf))
                    buf = ""
                segments.append(("icon", EMOJI_TO_ICON[key]))
                i += klen
                matched = True
                break

        if not matched:
            cp = ord(text[i])
            if _is_strippable_emoji(cp):
                # Unknown emoji / modifier — flush buffer, discard char
                if buf:
                    segments.append(("text", buf))
                    buf = ""
                i += 1
            else:
                buf += text[i]
                i += 1

    if buf:
        segments.append(("text", buf))

    return segments


def load_icon(name: str, size: int) -> "Image.Image | None":
    """Load a pre-baked icon PNG and return it as an RGBA image at *size*×*size*.

    Looks for ``app/assets/icons/{size}/{name}.png`` first; if the exact-size
    directory does not contain the icon, falls back through
    :data:`_ICON_FALLBACK_SIZES` (smallest first) and rescales with LANCZOS.

    Returns *None* if no matching PNG can be found (icon is silently skipped).
    """
    from PIL import Image  # local import to keep module importable without PIL

    # Build candidate paths: exact requested size first, then fallbacks
    candidates = [ICONS_DIR / str(size) / f"{name}.png"]
    for fb in _ICON_FALLBACK_SIZES:
        if fb != size:
            candidates.append(ICONS_DIR / str(fb) / f"{name}.png")

    src_path: Path | None = next((p for p in candidates if p.exists()), None)
    if src_path is None:
        return None

    try:
        img = Image.open(src_path).convert("RGBA")
        if img.size != (size, size):
            img = img.resize((size, size), Image.LANCZOS)
        return img
    except Exception:
        return None
